"""Session lifecycle hook payloads (D4/D5).

Both agents fire a hook when a turn ends and when a session starts, but they
consume the output differently — see `stop_payload`. Hook wiring is generated by
sync.py; these functions produce the JSON each agent expects on stdout.
"""

from __future__ import annotations

import re
from pathlib import Path

from .config import Config
from .context import build_project_context
from .memory import MemoryStore

CLAUDE = "claude-code"
CODEX = "codex"

# The session-end prompt. This is the whole of D4: rather than calling an
# external model to summarize (which would need an API key), we hand the
# instruction back to the agent's own already-running model.
NUDGE = (
    "Before you finish: did you learn anything durable and non-obvious about this project "
    "in this session — a decision, a gotcha, a convention, or a preference? "
    "If so, save each one now with the `memory_write` tool so the other agent "
    "(Claude Code or Codex) can use it in a later session. "
    "Save only what isn't already obvious from reading the codebase, and keep each memory "
    "to one self-contained fact. If there is nothing worth saving, say so briefly and stop."
)

_SAFE_SESSION_ID = re.compile(r"[^A-Za-z0-9._-]")


def _marker_path(cfg: Config, session_id: str) -> Path:
    safe = _SAFE_SESSION_ID.sub("_", session_id or "unknown")[:128]
    return cfg.state_dir / f"{safe}.nudged"


def already_nudged(cfg: Config, session_id: str) -> bool:
    return _marker_path(cfg, session_id).exists()


def mark_nudged(cfg: Config, session_id: str) -> None:
    path = _marker_path(cfg, session_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.touch()


def session_start_payload(agent: str, payload: dict, cfg: Config, store: MemoryStore) -> dict:
    """Seed the session with shared context (D5).

    Both agents accept `hookSpecificOutput.additionalContext` on SessionStart.
    """
    if not cfg.inject_context_on_start:
        return {}
    return {
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": build_project_context(cfg, store, limit=cfg.max_results * 2),
        }
    }


def stop_payload(agent: str, payload: dict, cfg: Config) -> dict:
    """Nudge the in-session model to persist what it learned (D4).

    The two agents diverge here, and getting this wrong silently breaks the nudge:

    - Claude Code: `reason` is shown to the *user*, not to Claude. Claude only
      sees `hookSpecificOutput.additionalContext`. So we send both — `decision:
      block` to prevent the stop, `additionalContext` to carry the instruction.
    - Codex: `reason` *is* the continuation prompt — it "acts as a new user
      prompt" — so the instruction goes there.

    Fires at most once per session: both agents' Stop event fires on every turn,
    and blocking every turn would burn tokens and never terminate.
    """
    if not cfg.flush_memory_on_end:
        return {}
    if agent == CLAUDE and cfg.claude_auto_memory == "native":
        # User chose Claude's built-in Auto Memory on this side (§5.6 conflict).
        return {}

    # Claude sets this when it is already continuing because of a Stop hook.
    if payload.get("stop_hook_active"):
        return {}

    session_id = payload.get("session_id", "")
    if already_nudged(cfg, session_id):
        return {}
    mark_nudged(cfg, session_id)

    if agent == CODEX:
        return {"decision": "block", "reason": NUDGE}
    return {
        "decision": "block",
        "reason": "Prompting the agent to save durable memories before finishing.",
        "hookSpecificOutput": {"hookEventName": "Stop", "additionalContext": NUDGE},
    }
