"""Register the MCP server and hooks in both agents' configs.

Phase 1 covers §5.4 items 3-5 (MCP registration, hook registration, gitignore).
CLAUDE.md generation and native skill mirroring arrive in Phase 2.

Every writer here is idempotent: our entries are tagged by their `uac hook` /
`uac serve` command and replaced on re-run, so `uac sync` never duplicates and
never clobbers a user's own hooks or servers.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import tomlkit

from . import skills as skills_mod
from .config import Config
from .hooks import CLAUDE, CODEX

SERVER_NAME = "uac"
GITIGNORE_ENTRIES = (".agents/memory.db", ".agents/state/", ".claude/skills/")

GENERATED_HEADER = "<!-- GENERATED by uac sync — edit AGENTS.md instead -->"


def uac_command() -> list[str]:
    """A command that will resolve when a hook or agent spawns us.

    Prefers the installed console script; falls back to the current interpreter
    so this keeps working inside a venv that isn't on the agent's PATH.
    """
    found = shutil.which(SERVER_NAME)
    return [found] if found else [sys.executable, "-m", "uac"]


def _hook_entry(agent: str, event: str) -> dict:
    cmd = " ".join(uac_command() + ["hook", event, "--agent", agent])
    return {"type": "command", "command": cmd}


def _is_ours(entry: dict) -> bool:
    hooks = entry.get("hooks", [])
    return any("hook session-start" in h.get("command", "") or "hook stop" in h.get("command", "")
               for h in hooks)


def _merge_hooks(existing: dict, agent: str, start_matcher: str) -> dict:
    """Replace our hook entries, leave everyone else's alone."""
    hooks = existing.setdefault("hooks", {})
    for event, cli_event, matcher in (
        ("SessionStart", "session-start", start_matcher),
        ("Stop", "stop", None),
    ):
        others = [e for e in hooks.get(event, []) if not _is_ours(e)]
        entry: dict = {"hooks": [_hook_entry(agent, cli_event)]}
        if matcher:
            entry["matcher"] = matcher
        hooks[event] = others + [entry]
    return existing


def _read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    text = path.read_text().strip()
    if not text:
        return {}
    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path} is not valid JSON — fix or remove it, then re-run: {exc}")


def _write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


# --- Claude Code -------------------------------------------------------------


def register_claude_mcp(cfg: Config) -> Path:
    """Project-scoped MCP server for Claude Code (.mcp.json at the repo root)."""
    path = cfg.root / ".mcp.json"
    data = _read_json(path)
    servers = data.setdefault("mcpServers", {})
    cmd = uac_command()
    servers[SERVER_NAME] = {
        "command": cmd[0],
        "args": cmd[1:] + ["serve"],
        # Each agent spawns its own stdio server, so env is how we attribute
        # writes to the right agent (config.current_source).
        "env": {"UAC_SOURCE": CLAUDE},
    }
    _write_json(path, data)
    return path


def register_claude_hooks(cfg: Config) -> Path:
    path = cfg.root / ".claude" / "settings.json"
    data = _merge_hooks(_read_json(path), CLAUDE, "startup|resume|clear|compact")
    _allow_our_mcp_tools(data)
    _write_json(path, data)
    return path


def _allow_our_mcp_tools(settings: dict) -> None:
    """Pre-approve our own MCP tools.

    Without this the whole layer silently does nothing: Claude asks to call
    mcp__uac__memory_write, the permission gate denies it, and the memory is
    never written — confirmed against the real CLI, which reported
    `permission_denials: [mcp__uac__memory_write]`. `mcp__uac` covers every tool
    the server exposes.

    These are our own local read/write tools over the user's own SQLite file, so
    allowing them is not a meaningful escalation.
    """
    allow = settings.setdefault("permissions", {}).setdefault("allow", [])
    rule = f"mcp__{SERVER_NAME}"
    if rule not in allow:
        allow.append(rule)


# --- Codex -------------------------------------------------------------------


def register_codex_mcp(cfg: Config) -> Path:
    """Project-scoped MCP server for Codex (.codex/config.toml).

    tomlkit preserves the user's existing formatting and comments.
    """
    path = cfg.root / ".codex" / "config.toml"
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = tomlkit.parse(path.read_text()) if path.exists() else tomlkit.document()

    servers = doc.get("mcp_servers")
    if servers is None:
        servers = tomlkit.table(is_super_table=True)
        doc["mcp_servers"] = servers

    cmd = uac_command()
    entry = tomlkit.table()
    entry["command"] = cmd[0]
    entry["args"] = cmd[1:] + ["serve"]
    env = tomlkit.inline_table()
    env["UAC_SOURCE"] = CODEX
    entry["env"] = env
    servers[SERVER_NAME] = entry

    path.write_text(tomlkit.dumps(doc))
    return path


def register_codex_hooks(cfg: Config) -> Path:
    """Codex reads hooks.json next to its config; JSON avoids mutating TOML."""
    path = cfg.root / ".codex" / "hooks.json"
    data = _merge_hooks(_read_json(path), CODEX, "startup|resume")
    _write_json(path, data)
    return path


# --- housekeeping ------------------------------------------------------------


def ensure_gitignore(cfg: Config) -> Path:
    path = cfg.root / ".gitignore"
    lines = path.read_text().splitlines() if path.exists() else []
    missing = [e for e in GITIGNORE_ENTRIES if e not in lines]
    if missing:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# unified-agent-context")
        lines.extend(missing)
        path.write_text("\n".join(lines) + "\n")
    return path


def register_all(cfg: Config) -> list[Path]:
    return [
        register_claude_mcp(cfg),
        register_claude_hooks(cfg),
        register_codex_mcp(cfg),
        register_codex_hooks(cfg),
        ensure_gitignore(cfg),
    ]


# --- generated artifacts (Phase 2) -------------------------------------------
# Everything below is derived from AGENTS.md + .agents/skills/. Each generator
# is split into "what should the content be" and "write it", so `--check` can
# compare without touching the working tree.


def claude_md_content(cfg: Config) -> str:
    """CLAUDE.md is a thin pointer at AGENTS.md, plus Claude-only extras."""
    parts = [GENERATED_HEADER, "", "@AGENTS.md"]
    if cfg.claude_extra:
        parts += ["", "## Claude-specific", "", cfg.claude_extra]
    return "\n".join(parts) + "\n"


def _guard_hand_written_claude_md(cfg: Config) -> None:
    path = cfg.claude_md
    if path.exists() and GENERATED_HEADER not in path.read_text():
        raise SystemExit(
            f"{path} exists but wasn't generated by uac. Refusing to overwrite it.\n"
            f"Move your content into AGENTS.md, delete CLAUDE.md, then re-run `uac sync`."
        )


def generate_claude_md(cfg: Config) -> Path:
    _guard_hand_written_claude_md(cfg)
    cfg.claude_md.write_text(claude_md_content(cfg))
    return cfg.claude_md


def skill_mirror_files(cfg: Config) -> dict[Path, str]:
    """The native Claude skill mirror: .claude/skills/<name>/SKILL.md (D6).

    Codex reads the same source through skill_load over MCP, so this directory
    is generated and disposable — never edit it by hand.
    """
    out: dict[Path, str] = {}
    for skill in skills_mod.discover(cfg.root):
        body = f"---\nname: {skill.name}\ndescription: {skill.description}\n---\n\n{skill.body}\n"
        out[cfg.root / ".claude" / "skills" / skill.name / "SKILL.md"] = body
    return out


def mirror_skills(cfg: Config) -> list[Path]:
    wanted = skill_mirror_files(cfg)
    mirror_root = cfg.root / ".claude" / "skills"

    for path, body in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body)

    # Drop mirrors whose source skill is gone, or a deleted skill lingers forever.
    if mirror_root.is_dir():
        keep = {p.parent for p in wanted}
        for stale in mirror_root.iterdir():
            if stale.is_dir() and stale not in keep:
                shutil.rmtree(stale)

    return sorted(wanted)


def stale_paths(cfg: Config) -> list[str]:
    """What `uac sync --check` reports. Empty means the tree is in sync."""
    problems: list[str] = []

    if not cfg.claude_md.exists():
        problems.append("CLAUDE.md is missing")
    elif cfg.claude_md.read_text() != claude_md_content(cfg):
        problems.append("CLAUDE.md is out of date")

    wanted = skill_mirror_files(cfg)
    for path, body in wanted.items():
        rel = path.relative_to(cfg.root)
        if not path.exists():
            problems.append(f"{rel} is missing")
        elif path.read_text() != body:
            problems.append(f"{rel} is out of date")

    mirror_root = cfg.root / ".claude" / "skills"
    if mirror_root.is_dir():
        keep = {p.parent for p in wanted}
        for stale in mirror_root.iterdir():
            if stale.is_dir() and stale not in keep:
                problems.append(f"{stale.relative_to(cfg.root)} has no matching skill")

    return problems


def sync_all(cfg: Config) -> list[Path]:
    written = [generate_claude_md(cfg)]
    written += mirror_skills(cfg)
    written += register_all(cfg)
    return written
